server:
  port: 9000
spring:
  application:
    name: spring-zuul-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    sale:
      path: /sale/**
      serviceId: spring-zuul-sale